export const TIME_TYPE = {
  year: 'day',
  day: 'hour',
  hour: 'min',
}

export const TIME_PROP = {
  min: 60,
  hour: 24,
}

export const SOURCE_LIST: any = [
  {
    title: '微博',
    source: 'weibo',
    icon: 'weibo-icon.png',
    list: [],
  },
  {
    title: '头条',
    source: 'toutiao',
    icon: 'toutiao-icon.png',
    list: [],
  },
  {
    title: '抖音',
    source: 'douyin',
    icon: 'douyin-icon.png',
    list: [],
  },
  // {
  //   title: '陕西',
  //   source: 'shanxi',
  //   icon: 'shanxi-icon.png',
  //   list: [],
  // },
  // {
  //   title: '西安',
  //   source: 'xian',
  //   icon: 'xian-icon.png',
  //   list: [],
  // },
  // {
  //   title: '咸阳',
  //   source: 'xianyang',
  //   icon: 'xianyang-icon.png',
  //   list: [],
  // },
  {
    title: '广东',
    source: 'guangdong',
    icon: 'guangdong-icon.png',
    list: [],
  },
  {
    title: '深圳',
    source: 'shenzhen',
    icon: 'shenzhen-icon.png',
    list: [],
  },
  {
    title: '坪山',
    source: 'pingshan',
    icon: 'pingshan-icon.png',
    list: [],
  },
  {
    title: '澎湃',
    source: 'pengpai',
    icon: 'pengpai-icon.png',
    list: [],
  },
  {
    title: '百度',
    source: 'baidu',
    icon: 'baidu-icon.png',
    list: [],
  },
  {
    title: '知乎',
    source: 'zhihu',
    icon: 'zhihu-icon.png',
    list: [],
  },
  // {
  //   title: '触电新闻app',
  //   source: 'chudian',
  //   icon: 'chudian-icon.png',
  //   list: [],
  // },
  // {
  //   title: '读特新闻',
  //   source: 'dute',
  //   icon: 'dute-icon.png',
  //   list: [],
  // },
  // {
  //   title: '晶报数字报',
  //   source: 'jingbao',
  //   icon: 'jingbao-icon.png',
  //   list: [],
  // },
  // {
  //   title: '南方都市报',
  //   source: 'nandu',
  //   icon: 'nandu-icon.png',
  //   list: [],
  // },
  // {
  //   title: '南方都市报热点',
  //   source: 'nfhot',
  //   icon: 'nfhot-icon.png',
  //   list: [],
  // },
  // {
  //   title: '南方plus',
  //   source: 'nfplus',
  //   icon: 'nfplus-icon.png',
  //   list: [],
  // },
  // {
  //   title: '奥一网',
  //   source: 'oe',
  //   icon: 'oe-icon.png',
  //   list: [],
  // },
  // {
  //   title: '坪山新闻',
  //   source: 'psnews',
  //   icon: 'psnews-icon.png',
  //   list: [],
  // },
  // {
  //   title: '深圳论坛',
  //   source: 'szbbs',
  //   icon: 'szbbs-icon.png',
  //   list: [],
  // },
  // {
  //   title: '深圳家园论坛',
  //   source: 'szhome',
  //   icon: 'szhome-icon.png',
  //   list: [],
  // },

  // {
  //   title: '深圳新闻',
  //   source: 'sznews',
  //   icon: 'sznews-icon.png',
  //   list: [],
  // },
  // {
  //   title: '深圳plus',
  //   source: 'szplus',
  //   icon: 'szplus-icon.png',
  //   list: [],
  // },
  // {
  //   title: '深圳问政',
  //   source: 'szwz',
  //   icon: 'szwz-icon.png',
  //   list: [],
  // },
  // {
  //   title: '壹深圳',
  //   source: 'ysz',
  //   icon: 'ysz-icon.png',
  //   list: [],
  // },
  // {
  //   title: '人民网必看(坪山)',
  //   source: 'rmbkps',
  //   icon: 'rmbk-icon.png',
  //   list: [],
  // },
  // {
  //   title: '人民网必看(深圳)',
  //   source: 'rmbksz',
  //   icon: 'rmbk-icon.png',
  //   list: [],
  // },
  // {
  //   title: 'B站',
  //   source: 'bili',
  //   icon: 'bili-icon.png',
  //   list: [],
  // },
  // {
  //   title: '凤凰新闻',
  //   source: 'fenghuang',
  //   icon: 'fenghuang-icon.png',
  //   list: [],
  // },
  // {
  //   title: '好看视频',
  //   source: 'hk',
  //   icon: 'hk-icon.png',
  //   list: [],
  // },
  // {
  //   title: '金羊网',
  //   source: 'jinyang',
  //   icon: 'jinyang-icon.png',
  //   list: [],
  // },
  // {
  //   title: '快手',
  //   source: 'kuaishou',
  //   icon: 'kuaishou-icon.png',
  //   list: [],
  // },
  // {
  //   title: '搜狐',
  //   source: 'sohu',
  //   icon: 'sohu-icon.png',
  //   list: [],
  // },
  // {
  //   title: '贴吧',
  //   source: 'tieba',
  //   icon: 'tieba-icon.png',
  //   list: [],
  // },
  // {
  //   title: '网易新闻',
  //   source: 'wangyi',
  //   icon: 'wangyi-icon.png',
  //   list: [],
  // },
  // {
  //   title: '西瓜视频',
  //   source: 'xigua',
  //   icon: 'xigua-icon.png',
  //   list: [],
  // },
]
